---
git:
  url: "https://github.com/git-for-windows/git/releases/download/v2.10.1.windows.1/PortableGit-2.10.1-64-bit.7z.exe"
conemu:
  url: "https://github.com/Maximus5/ConEmu/releases/download/v16.10.09a/ConEmuPack.161009a.7z"
clink:
  url: "https://github.com/mridgers/clink/releases/download/0.4.8/clink_0.4.8.zip"
atom:
  url: "https://github.com/atom/atom/releases/download/v1.11.2/atom-windows.zip"
  plugins: 
    atom-beautify: ""
    minimap: ""
    line-ending-converter: ""
    language-chef: ""
    language-batchfile: ""
boot2docker:
  url: "https://github.com/boot2docker/boot2docker-cli/releases/download/v1.8.0/boot2docker-v1.8.0-windows-amd64.exe"
docker:
  url: "https://download.docker.com/win/stable/InstallDocker.msi"
ruby-devkit:
  url: "http://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe"
kdiff3:
  url: "http://downloads.sourceforge.net/project/kdiff3/kdiff3/0.9.98/KDiff3-64bit-Setup_0.9.98-2.exe"
putty:
  url: "https://the.earth.li/~sgtatham/putty/latest/x86/putty.zip"
cwrsync:
  url: "https://www.itefix.net/dl/cwRsync_5.5.0_x86_Free.zip"
vagrant:
  url: "https://releases.hashicorp.com/vagrant/1.8.6/vagrant_1.8.6.msi"
  plugins:
    vagrant-toplevel-cookbooks: "0.2.4"
    vagrant-omnibus: "1.4.1"
    vagrant-cachier: "1.2.1"
    vagrant-proxyconf: "1.5.2"
    vagrant-berkshelf: "4.1.0"
    vagrant-winrm: "0.7.0"
terraform:
  url: "https://releases.hashicorp.com/terraform/0.7.7/terraform_0.7.7_windows_amd64.zip"
packer:
  url: "https://releases.hashicorp.com/packer/0.10.2/packer_0.10.2_windows_amd64.zip"
consul:
  url: "https://releases.hashicorp.com/consul/0.7.0/consul_0.7.0_windows_amd64.zip"
chefdk:
  url: "https://packages.chef.io/stable/windows/2008r2/chefdk-0.18.30-1-x86.msi"
  plugins: 
    knife-audit: "0.2.0"
    knife-server: "1.1.0"
   